# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

# ignore all warnings from all pods
inhibit_all_warnings!

# Shared pods
def shared_pods

    # Network
    pod 'Alamofire', '~> 5.0'
    pod 'OHHTTPStubs/Swift'

    # Linting
    pod 'SwiftLint', '~> 0.39.2'

    # Tooling
    pod 'RxCocoa', '~> 5.1'
    pod 'RxSwift', '~> 5.1'

    pod 'FlagKit', :git =>'https://github.com/madebybowtie/FlagKit.git', :tag => '2.4.0'
end

target 'cov-stats' do
  shared_pods

  target 'cov-statsTests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end

